<script setup lang="ts">
import { reactive } from 'vue'
import { Play, Sparkles } from 'lucide-vue-next'
import StatPill from '../components/StatPill.vue'
import { useGameStore } from '../stores/game'
const emit = defineEmits<{ played: [] }>(); const store = useGameStore(); const choices = reactive<Record<string,string>>({})
const strategies = [
 {key:'training', label:'Entrenamiento', options:[['Bajo','Menos riesgo'],['Normal','Progreso estable'],['Alto','Máxima mejora']]},
 {key:'money', label:'Dinero', options:[['Ahorrar','Protege tu futuro'],['Bienestar','Disfruta el presente'],['Invertir','Haz crecer capital']]},
 {key:'image', label:'Imagen', options:[['Perfil bajo','Menos presión'],['Equilibrado','Control y alcance'],['Mediático','Máxima fama']]},
 {key:'career', label:'Carrera', options:[['Minutos','Jugar siempre'],['Dinero','Mejor contrato'],['Títulos','Buscar la gloria']]},
] as const
function play(){ store.playSeason(choices); emit('played') }
</script>
<template><main v-if="store.state" class="game-shell"><header class="topbar"><div class="brand small">COPERO</div><div class="season-label">TEMPORADA <strong>{{ store.state.player.season }}</strong></div><div class="player-mini"><b>{{ store.state.player.name }}</b><span>{{ store.state.player.club }}</span></div></header><section class="dashboard"><div class="identity"><p>{{ store.state.player.position.toUpperCase() }} · {{ store.state.player.country.toUpperCase() }}</p><h1>{{ store.state.player.name }}</h1><div class="stats-row"><StatPill label="EDAD" :value="store.state.player.age"/><StatPill label="MEDIA" :value="store.state.player.rating"/><StatPill label="FORMA" :value="store.state.player.fitness"/><StatPill label="PATRIMONIO" :value="`${store.state.player.wealth.toFixed(1)} M€`"/></div></div><div class="columns"><section class="panel decisions"><div class="panel-heading"><span>01</span><div><h2>Tu plan de temporada</h2><p>Cuatro decisiones. Un año de consecuencias.</p></div></div><div v-for="strategy in strategies" :key="strategy.key" class="strategy"><h3>{{ strategy.label }}</h3><div class="option-grid"><button v-for="option in strategy.options" :key="option[0]" :class="{selected:store.state.strategies[strategy.key]===option[0]}" @click="store.state.strategies[strategy.key]=option[0]"><b>{{ option[0] }}</b><span>{{ option[1] }}</span></button></div></div></section><section class="panel events"><div class="panel-heading"><span>02</span><div><h2>La temporada te espera</h2><p>Elige cómo responder a cada momento.</p></div></div><article v-for="event in store.currentEvents" :key="event.id" class="event-card"><div class="event-tag"><Sparkles :size="13"/> {{ event.category }}</div><h3>{{ event.title }}</h3><p>{{ event.description }}</p><label v-for="choice in event.choices" :key="choice.id" class="choice" :class="{chosen:(choices[event.id]||event.choices[0].id)===choice.id}"><input v-model="choices[event.id]" type="radio" :name="event.id" :value="choice.id"/><span><b>{{ choice.label }}</b><small>{{ choice.description }}</small></span></label></article></section></div><button class="play-button" @click="play"><span><Play fill="currentColor" :size="18"/> JUGAR TEMPORADA {{ store.state.player.season }}</span><small>Simular resultados</small></button></section></main></template>
